config/routes.rb
Rails.application.routes.draw do
  resources :themes
  root to: "themes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThemeGenerator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/themes/_form.html.erb
<%= form_with(model: theme, local: true) do |form| %>
  <% if theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
      <% theme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :theme_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :theme_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/themes/edit.html.erb
<h1>Editing Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>

app/views/themes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Themes</h1>

<table>
  <thead>
    <tr>
      <th>Name!!!!!</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @themes.each do |theme| %>
      <tr>
        <td><%= theme.name %></td>
        <td><%= theme.description %></td>
        <td><%= link_to 'Show', theme %></td>
        <td><%= link_to 'Edit', edit_theme_path(theme) %></td>
        <td><%= link_to 'Destroy', theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theme', new_theme_path %>

app/views/themes/new.html.erb
<h1>New Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Back', themes_path %>

app/views/themes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @theme.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @theme.description %>
</p>

<%= link_to 'Edit', edit_theme_path(@theme) %> |
<%= link_to 'Back', themes_path %>